# .github/workflows/build-windows.yml

name: Build Digital Twin Monitoring System for Windows

# 触发条件：
# 1. 当代码被推送到 main 分支时
# 2. 或者当您在 GitHub Actions 页面手动触发时
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows-app:
    # 运行环境：最新的 Windows Server
    runs-on: windows-latest

    steps:
      # 第1步：检出您的代码库
      - name: Check out repository code
        uses: actions/checkout@v4

      # 第2步：设置 Python 环境
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 锁定到您本地使用的Python版本，以保证一致性

      # 第3步：安装所有依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 从 requirements.txt 一次性安装所有库
          pip install -r requirements.txt

      # 第4步：使用 PyInstaller 打包成 .exe 文件
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed `
            --name="DigitalTwinSystem" `
            --icon="assets/icon.ico" `
            --add-data="C:/Python39/Lib/site-packages/pyvista/core/pyvista_ndarray.py;pyvista/core" `
            --hidden-import="pyvista.core.errors" `
            --hidden-import="vtkmodules.all" `
            --hidden-import="vtkmodules.qt.QVTKRenderWindowInteractor" `
            main.py
      
      # 第5步：上传构建好的 .exe 文件作为 "Artifact"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # 上传后的产物名称
          name: Digital-Twin-System-Windows
          # 要上传的文件的路径
          path: dist/DigitalTwinSystem.exe